export type ContentCard = { title: string; text: string };
export type ContentSection =
  | { type: "cards"; heading: string; intro?: string[]; cards: ContentCard[] }
  | { type: "checklist"; heading: string; body: string[]; checklistHeading: string; items: string[] }
  | { type: "feature"; heading: string; body: string[]; link?: { label: string; href: string } }
  | { type: "process"; heading: string; steps: ContentCard[] }
  | { type: "faq"; heading: string; faqs: { question: string; answer: string; link?: { label: string; href: string } }[] };

export type ServiceContent = {
  slug: string; navTitle: string; title: string; description: string; h1: string; intro: string[]; heroButton: string;
  sections: ContentSection[]; serviceAreaHeading: string; serviceAreaText: string;
  finalTitle: string; finalText: string; finalButton: string;
};

export const servicePages: ServiceContent[] = [
  {
    slug: "roof-inspections", navTitle: "Roof Inspections",
    title: "Roof Inspections in Zionsville & Central Indiana | Centerline",
    description: "Get clear answers about the condition of your roof. Centerline provides professional roof inspections for homeowners throughout Central Indiana.",
    h1: "A Better Roof Inspection Starts With Knowing What to Look For",
    intro: ["Whether you've noticed a problem, recently experienced a storm, or simply want to understand the condition of your roof, a thorough inspection gives you a place to start. We'll evaluate your roofing system, explain what we find, and help you understand whether anything needs attention now—or whether your roof is doing exactly what it should."], heroButton: "Request a Free Roof Inspection",
    sections: [
      { type: "cards", heading: "You Don't Have to Wait for a Leak to Have Your Roof Inspected", intro: ["Some roofing problems are obvious. Others can develop long before water shows up inside your home. An inspection can help identify damage, deterioration, installation concerns, or areas that deserve attention before they become larger problems."], cards: [
        { title: "After a Storm", text: "Wind, hail, falling debris, and severe weather can cause damage that isn't always obvious from the ground." },
        { title: "When You Notice a Problem", text: "Missing shingles, water stains, unusual wear, or other changes around your home are good reasons to take a closer look." },
        { title: "An Aging Roof", text: "As a roof gets older, an inspection can help you understand its overall condition and begin planning for future maintenance or replacement." },
        { title: "Before Buying a Home", text: "A roof can represent a significant future expense. Understanding its condition can provide valuable information when evaluating a home." },
        { title: "Before Selling a Home", text: "Knowing the condition of your roof before listing can help identify potential concerns and reduce surprises during the selling process." },
        { title: "For Peace of Mind", text: "Sometimes you simply want to know how your roof is doing. If everything looks good, we'll tell you that too." },
      ] },
      { type: "cards", heading: "We Look at the Roof as a Complete System", intro: ["A roof inspection should involve more than looking for missing shingles. We'll evaluate the condition of the roofing system and the critical areas that can affect how well it protects your home. When accessible and relevant to the concern, we'll also look inside the attic for signs that can help us better understand what's happening above."], cards: [
        { title: "Shingles & Roofing Materials", text: "We'll look for visible wear, damage, deterioration, missing materials, and other conditions that may affect performance." },
        { title: "Flashing & Roof Transitions", text: "We'll evaluate visible flashing and critical transition areas around walls, chimneys, valleys, and other locations where water intrusion can occur." },
        { title: "Vents & Penetrations", text: "We'll inspect visible plumbing vents, exhaust vents, skylights, and other roof penetrations for signs of damage or potential water-entry points." },
        { title: "Gutters & Roof Edges", text: "We'll look at roof edges, drainage areas, and visible gutter conditions that may affect how water moves away from the roofing system." },
        { title: "Ventilation & Attic Conditions", text: "We'll evaluate visible ventilation conditions and, when attic access is available and appropriate, look for signs of moisture intrusion, staining, condensation, or other conditions that may help us understand how the roofing system is performing." },
        { title: "Overall Roof Condition", text: "We'll consider the age, visible condition, previous repairs, and overall performance of the roofing system—not simply one isolated area." },
      ] },
      { type: "feature", heading: "An Inspection Should Give You Answers, Not More Questions", body: ["Once we've evaluated your roof, we'll walk you through what we found and explain what it means for your home.", "If your roof is in good condition and doesn't need work, we'll tell you.", "If there's a problem that can be repaired, we'll explain the repair and why we recommend it.", "If the condition of the roof makes replacement the better long-term solution, we'll explain what we're seeing, why replacement may make sense, and what your options are.", "You'll leave the inspection with a clear understanding of your roof, what—if anything—needs attention, and the options available to you."] },
      { type: "process", heading: "What to Expect From a Centerline Roof Inspection", steps: [
        { title: "Understand Your Concerns", text: "We'll start by talking with you about what you've noticed, the history of the roof, any recent weather events, and any specific concerns you want us to investigate." },
        { title: "Inspect", text: "We'll evaluate the roof and relevant components of the roofing system, paying particular attention to areas where damage, deterioration, or water intrusion commonly occur." },
        { title: "Document & Explain", text: "We'll document relevant findings and walk you through what we're seeing so you understand the condition of your roof and any areas that deserve attention." },
        { title: "Recommend the Next Step", text: "If nothing needs to be done, we'll tell you. If maintenance, repair, replacement, or further evaluation is appropriate, we'll explain why and help you understand your options." },
      ] },
      { type: "faq", heading: "Roof Inspection FAQs", faqs: [
        { question: "How often should I have my roof inspected?", answer: "It's a good idea to pay attention to your roof throughout its life, particularly after significant storms or anytime you notice a change. As an asphalt-shingle roof reaches roughly 10–15 years of age, having its condition professionally evaluated periodically can also help identify developing issues and give you a better idea of what to expect in the years ahead. Roof age alone doesn't determine when replacement is necessary—the materials, installation, ventilation, weather exposure, and maintenance all affect how a roof ages." },
        { question: "Do I need to see a leak before having my roof inspected?", answer: "No. Some roofing issues can exist before water becomes visible inside the home. Missing or damaged shingles, flashing problems, storm damage, and other concerns may be visible during an inspection before they result in an interior leak." },
        { question: "Should I have my roof inspected after a storm?", answer: "If your home has been affected by significant wind, hail, falling debris, or other severe weather, having the roof inspected can help identify damage that may not be visible from the ground. We'll evaluate the roof, document relevant findings, and explain whether anything needs attention.", link: { label: "Learn About Storm Damage Restoration", href: "/storm-damage-restoration" } },
        { question: "What will you recommend after the inspection?", answer: "That depends entirely on what we find. Your roof may need nothing at all, a specific repair may make sense, or its overall condition may make replacement worth considering. We'll explain what we're seeing, why it matters, and the options available so you can make an informed decision." },
      ] },
    ], serviceAreaHeading: "Roof Inspections in Zionsville & Central Indiana", serviceAreaText: "Centerline Roofing & Exteriors provides residential roof inspections throughout Zionsville, Carmel, Westfield, Whitestown, Brownsburg, Lebanon, and surrounding Central Indiana communities.", finalTitle: "Not Sure What Your Roof Needs? Start With an Inspection.", finalText: "We'll take the time to understand your concerns, evaluate your roof, and explain exactly what we find. Whether you need a repair, replacement, or nothing at all, you'll have a clear answer about what to do next.", finalButton: "Request a Free Roof Inspection",
  },
  {
    slug: "roof-repair", navTitle: "Roof Repair", title: "Roof Repair in Zionsville & Central Indiana | Centerline",
    description: "Roof leak, missing shingles or other damage? Centerline diagnoses roofing problems and provides residential roof repair throughout Central Indiana.", h1: "Roof Repair Starts With Finding the Real Problem",
    intro: ["A leak, missing shingles, damaged flashing, or another roofing issue doesn't automatically mean you need a new roof. We'll thoroughly inspect the problem, help you understand what's causing it, and recommend the right repair when a repair is the right solution."], heroButton: "Request a Free Roof Inspection",
    sections: [
      { type: "checklist", heading: "A Roofing Problem Doesn't Always Mean a New Roof", body: ["Roofing problems can show up in obvious ways—like a missing shingle—or as something much harder to diagnose, such as a small leak that only appears during certain weather conditions.", "The key is identifying where the problem is actually coming from and understanding the condition of the surrounding roofing system. We'll inspect the affected area, look for contributing issues, and determine whether a targeted repair can properly solve the problem."], checklistHeading: "Signs Your Roof May Need Attention", items: ["Missing, lifted, cracked, or damaged shingles", "Water stains on ceilings or walls", "Leaks during or after heavy rain", "Damage around chimneys, vents, skylights, or roof penetrations", "Loose, deteriorated, or improperly installed flashing", "Damage caused by wind, hail, branches, or debris", "Exposed or damaged roofing materials"] },
      { type: "cards", heading: "Common Roof Repairs", intro: ["Not every roofing issue has the same cause—or the same solution. These are some of the common problems we evaluate and repair on residential roofing systems."], cards: [
        { title: "Shingle Damage", text: "Missing, cracked, lifted, or otherwise damaged shingles can leave the roofing system vulnerable to water and further deterioration." }, { title: "Flashing Repairs", text: "Flashing protects some of the most vulnerable areas of your roof, including transitions around chimneys, walls, valleys, and other roof details." }, { title: "Roof Leaks", text: "The place where water appears inside your home isn't always where it entered the roofing system. Proper leak repair starts with finding the actual source." }, { title: "Vent & Penetration Repairs", text: "Plumbing vents, exhaust vents, skylights, and other roof penetrations require properly installed and maintained waterproofing details." }, { title: "Storm & Wind Damage", text: "High winds, hail, falling branches, and severe weather can damage individual sections of an otherwise serviceable roof." }, { title: "Minor Decking & Roofing-System Repairs", text: "When localized deterioration affects the materials beneath the shingles, the repair may require addressing more than the visible surface to properly restore the affected area." },
      ] },
      { type: "feature", heading: "Repair or Replace? We'll Help You Understand the Difference.", body: ["Sometimes a repair is exactly what a roof needs. Other times, repairing one area of a roof that is significantly deteriorated or near the end of its useful life may only postpone a larger problem.", "We'll consider the age and overall condition of your roof, the extent and location of the damage, previous repairs, material availability, and the expected life of the repair before making a recommendation.", "If a repair is the practical solution, we'll tell you. If replacement makes more sense, we'll explain what we're seeing and why. Either way, you'll have the information you need to make a confident decision about your home."], link: { label: "Learn About Roof Replacement", href: "/roof-replacement" } },
      { type: "cards", heading: "A Good Repair Solves the Problem, Not Just the Symptom", intro: ["The visible damage isn't always the entire problem. A lasting repair starts with understanding how water, materials, flashing, ventilation, and surrounding roof components are working together."], cards: [
        { title: "Find the Source", text: "Water can travel along decking, framing, or other materials before it becomes visible inside your home. We work to identify where the problem actually begins." }, { title: "Evaluate the Surrounding Roof", text: "A repair should account for the condition of the materials around the damaged area—not just the one shingle or component that appears to be failing." }, { title: "Use Compatible Materials", text: "Repair materials should integrate properly with the existing roofing system and provide a durable solution." }, { title: "Address the Cause", text: "When installation details, flashing, ventilation, or another underlying issue contributed to the problem, simply covering the visible damage may not solve it." },
      ] },
      { type: "process", heading: "What to Expect From a Centerline Roof Repair", steps: [
        { title: "Inspect", text: "We'll start by listening to what you've noticed and thoroughly evaluating the affected area and surrounding roofing system to identify the source and extent of the problem." }, { title: "Explain", text: "We'll show you what we found, explain what's causing the issue, and discuss whether repair is the appropriate solution." }, { title: "Repair", text: "When a repair makes sense, we'll establish the scope of work and complete the repair using appropriate materials and installation methods for the roofing system." }, { title: "Review", text: "We'll review the completed work, explain what was repaired, answer your questions, and make sure you understand anything you should continue to watch or maintain." },
      ] },
      { type: "faq", heading: "Roof Repair FAQs", faqs: [
        { question: "Can my roof be repaired instead of replaced?", answer: "Often, yes. Whether repair makes sense depends on the type and extent of the damage, the age and condition of the roof, previous repairs, and whether suitable materials are available. We'll inspect the roof before recommending either option." }, { question: "How do you find the source of a roof leak?", answer: "We start with what you're seeing inside the home—where and when the leak appears—then inspect the roof and surrounding components for likely entry points. That may include shingles, flashing, valleys, vents, penetrations, transitions, and other vulnerable areas. Because water can travel before becoming visible inside, we'll look beyond the obvious symptom to identify the actual source of the intrusion." }, { question: "How quickly should I address a roof leak?", answer: "Roof leaks should be evaluated as soon as reasonably possible. Even a small amount of water intrusion can affect decking, insulation, ceilings, walls, and other materials if the source continues." }, { question: "Do you repair storm-damaged roofs?", answer: "Yes. Localized storm damage can sometimes be repaired when the surrounding roofing system remains in good condition. When damage is more widespread, we'll explain what we find and whether a larger restoration may be appropriate.", link: { label: "Learn About Storm Damage Restoration", href: "/storm-damage-restoration" } },
      ] },
    ], serviceAreaHeading: "Roof Repair in Zionsville & Central Indiana", serviceAreaText: "Centerline Roofing & Exteriors provides residential roof repair throughout Zionsville, Carmel, Westfield, Whitestown, Brownsburg, Lebanon, and surrounding Central Indiana communities.", finalTitle: "Something Wrong With Your Roof? Let's Find Out What It Is.", finalText: "You don't need to know whether you need a repair or replacement before calling us. Start with an inspection. We'll evaluate the problem, explain what we find, and help you determine the right next step.", finalButton: "Request a Free Roof Inspection",
  },
  {
    slug: "roof-replacement", navTitle: "Roof Replacement", title: "Roof Replacement in Zionsville & Central Indiana | Centerline",
    description: "Centerline provides residential roof replacement with clear guidance, quality roofing systems and professional installation throughout Central Indiana.", h1: "Roof Replacement Built Around Your Home",
    intro: ["Replacing your roof is a significant investment, and the right solution involves more than choosing a shingle. We'll help you understand the condition of your current roof, compare your options, and build a complete roofing system using premium materials selected for your home, your goals, and long-term performance."], heroButton: "Request a Free Roof Inspection",
    sections: [
      { type: "checklist", heading: "When Is It Time to Replace Your Roof?", body: ["Not every roofing problem requires a new roof. Before recommending replacement, we'll evaluate the condition of your existing roof and determine whether repairing it still makes sense. When age, widespread damage, recurring problems, or the overall condition of the roofing system makes replacement the better investment, we'll explain what we're seeing and why."], checklistHeading: "Signs It May Be Time to Consider Replacement", items: ["Widespread cracked, curling, brittle, or missing shingles", "Recurring leaks or repairs in multiple areas", "Significant granule loss or deterioration", "Widespread hail or wind damage", "Soft, damaged, or deteriorated roof decking", "An aging roof approaching the end of its useful life", "Discontinued or difficult-to-match roofing materials", "Ventilation or installation problems affecting roof performance"] },
      { type: "cards", heading: "A Roof Is More Than the Shingles You See", intro: ["A quality roof replacement isn't simply removing old shingles and installing new ones. Your roof is a complete system, and each component plays a role in protecting your home from water, wind, heat, moisture, and Indiana weather.", "When we plan your replacement, we'll evaluate the entire system—including the decking, underlayment, flashing, ventilation, valleys, penetrations, edge protection, and other critical details—not just the shingles that are visible from the street."], cards: [
        { title: "Decking", text: "The structural surface supporting your roofing system." }, { title: "Underlayment & Water Protection", text: "Additional protection beneath the shingles, particularly in vulnerable areas." }, { title: "Flashing & Penetrations", text: "Critical details around chimneys, walls, vents, valleys, and other areas where water intrusion commonly begins." }, { title: "Ventilation", text: "A properly designed intake and exhaust ventilation system helps manage heat and moisture in the attic, supports the long-term performance of your roof, and can help reduce the conditions that contribute to ice dams during Indiana winters." }, { title: "Shingles & Roofing Materials", text: "The visible layer of the system, selected for performance, durability, appearance, warranty, and the needs of your home." },
      ] },
      { type: "feature", heading: "Premium Materials. The Right System for Your Home.", body: ["We believe exceptional results start with exceptional materials. That's why Centerline works with premium roofing products from manufacturers we trust rather than building projects around the cheapest available option.", "But the most expensive product isn't automatically the right product. We'll help you compare materials, performance, warranties, appearance, and cost so you can choose a roofing system that makes sense for your home and what you want to accomplish."] },
      { type: "process", heading: "What Goes Into a Centerline Roof Replacement", steps: [
        { title: "Inspect & Evaluate", text: "We start by evaluating your existing roof and the details that affect its performance. We'll document what we find and make sure replacement is actually the right recommendation before planning a new roofing system." }, { title: "Design the Right System", text: "We'll help you select materials, colors, ventilation, and roofing components based on your home's architecture, current conditions, performance and design goals, and budget." }, { title: "Prepare & Protect", text: "Before installation begins, we'll establish the project plan, communicate what to expect, coordinate materials and scheduling, and prepare to protect your home and property throughout the work." }, { title: "Install With Attention to Detail", text: "Experienced roofing professionals complete the installation according to the project specifications and applicable manufacturer requirements, with attention given to the details that determine how the entire roofing system performs." }, { title: "Inspect, Clean & Walk Through", text: "Once the project is complete, we'll inspect the finished work, thoroughly clean the jobsite, and walk the project with you so you understand what was completed and have an opportunity to ask any remaining questions." },
      ] },
      { type: "cards", heading: "Choosing the Right Roof", intro: ["Your roof is one of the largest visual elements of your home's exterior. The right roofing system should protect the home exceptionally well while also complementing its architecture.", "We'll help you evaluate the differences that actually matter—including shingle construction, impact resistance, warranty options, color, dimensional appearance, ventilation requirements, and long-term value—so you're not left trying to compare products based on a stack of manufacturer brochures."], cards: [
        { title: "Architectural Shingles", text: "A strong combination of performance, dimensional appearance, availability, and value for many Central Indiana homes." }, { title: "Premium / Designer Shingles", text: "Enhanced profiles, colors, shadow lines, and design options for homeowners looking for a more distinctive architectural appearance." }, { title: "Impact-Resistant Options", text: "Products designed for increased resistance to hail impact and severe weather, where appropriate for the home and homeowner's priorities." },
      ] },
      { type: "faq", heading: "Roof Replacement FAQs", faqs: [
        { question: "How do I know whether I need a roof repair or a full replacement?", answer: "It depends on the age and overall condition of your roof, the extent of the damage, previous repairs, material condition, and whether the problem is isolated or widespread. We'll inspect the roof first and recommend repair when repair is still the practical solution." }, { question: "How long does a roof replacement take?", answer: "Many residential roof replacements can be completed relatively quickly, but the actual timeline depends on the size and complexity of the roof, weather, material selection, decking condition, and the scope of work. We'll establish expectations and scheduling before your project begins." }, { question: "What happens if damaged decking is discovered after the old roof is removed?", answer: "The condition of every part of the decking can't always be confirmed until the existing roofing materials are removed. If we discover damaged or deteriorated decking, we'll document it, explain what needs to be addressed, and communicate with you before moving forward with additional work." }, { question: "Can you help me choose the right shingles for my home?", answer: "Absolutely. We'll help you compare material quality, performance, warranty options, color, appearance, and cost so you understand the differences and can select the roofing system that best fits your home and priorities." }, { question: "Will you protect my property and clean up after the installation?", answer: "Yes. Property protection and cleanup are part of a professional roofing project. We'll plan for landscaping, siding, driveways, outdoor areas, and other vulnerable parts of your property, then complete a thorough cleanup and final walkthrough when the work is finished." },
      ] },
    ], serviceAreaHeading: "Serving Zionsville & Central Indiana", serviceAreaText: "Centerline Roofing & Exteriors provides residential roof replacement throughout Zionsville, Carmel, Westfield, Whitestown, Brownsburg, Lebanon, and surrounding Central Indiana communities.", finalTitle: "Ready to Find the Right Roof for Your Home?", finalText: "Start with a free inspection. We'll evaluate your current roof, answer your questions, and help you determine the right roofing system for your home.", finalButton: "Request a Free Roof Inspection",
  },
  {
    slug: "storm-damage-restoration", navTitle: "Storm Damage Restoration", title: "Storm Damage Roofing & Restoration | Centerline",
    description: "Centerline inspects and documents storm damage and helps Central Indiana homeowners navigate roof and exterior restoration after severe weather.", h1: "Think Your Home May Have Storm Damage? Start Here.",
    intro: ["Hail, high winds, and severe weather can damage your roof and exterior in ways that aren't always visible from the ground. We'll thoroughly inspect your home, document what we find, explain the damage, and help you understand what to do next—including how the restoration process works when insurance is involved."], heroButton: "Request a Free Storm Damage Inspection",
    sections: [
      { type: "checklist", heading: "Your Home Can Be Damaged Even When Everything Looks Fine From the Ground", body: ["Some storm damage is easy to spot. Missing shingles, fallen branches, or damaged siding make it clear that something happened.", "Other damage can be much less obvious. Hail can affect roofing materials without creating an immediate leak, and high winds can loosen or damage shingles and exterior components in ways that aren't easy to see from the ground.", "If you suspect your home was affected by a storm, the first step is understanding what actually happened."], checklistHeading: "Signs Your Home May Have Storm Damage", items: ["Missing, lifted, creased, torn, or damaged shingles", "Hail impacts or unusual granule loss on roofing materials", "Damage to flashing, vents, or other roof components", "Dents or impact marks on gutters and downspouts", "Cracked, dented, or damaged siding", "Fallen limbs or debris impacting the roof", "Water stains, leaks, or other signs of water intrusion", "Visible changes to your roof or exterior after a storm"] },
      { type: "cards", heading: "Understanding Storm Damage", intro: ["Different types of severe weather affect your home in different ways. A thorough inspection helps determine what was damaged, how extensive the damage is, and what may need to be repaired or replaced."], cards: [
        { title: "Hail Damage", text: "Hail can damage shingles and other exterior materials, affecting protective surfaces and potentially reducing the long-term performance of the roofing system." }, { title: "Wind Damage", text: "High winds can lift, loosen, crease, tear, or remove shingles and can also damage flashing, vents, siding, gutters, and other exterior components." }, { title: "Falling Debris", text: "Tree limbs and wind-driven debris can cause anything from localized damage to more significant impacts requiring immediate attention." }, { title: "Water Intrusion", text: "When a storm compromises part of the roofing system, water can enter through damaged shingles, flashing, penetrations, or other vulnerable areas and affect materials inside the home." },
      ] },
      { type: "feature", heading: "First, Let's Understand the Damage.", body: ["After a storm, it's easy to have questions about what happened, whether your home was damaged, and what you're supposed to do next.", "We'll start by thoroughly inspecting the affected areas, documenting what we find, and helping you understand the condition of your home. From there, we'll explain whether the damage can be repaired, whether more extensive restoration may be needed, and what the next steps look like.", "You shouldn't have to make decisions about your home before you understand the problem."] },
      { type: "feature", heading: "If Insurance Is Involved, We'll Help You Through the Process", body: ["Dealing with storm damage can be stressful, especially when an insurance claim is involved. We'll help you understand what to expect, document the damage we find, answer your questions, and guide you through the restoration process from inspection through completion.", "When needed, we'll work with your insurance adjuster and provide clear documentation and information about the damage and the scope of work needed to properly restore your home.", "You won't have to navigate the process alone. We'll be there to help you understand what comes next and keep the restoration moving forward."] },
      { type: "process", heading: "What to Expect After Storm Damage", steps: [
        { title: "Inspect", text: "We'll start by understanding your concerns and thoroughly inspecting the roof and relevant exterior areas for signs of storm damage." }, { title: "Document & Explain", text: "We'll document relevant findings, show you what we found, and explain the condition of the affected areas so you understand what happened to your home." }, { title: "Determine the Right Path Forward", text: "We'll evaluate whether the damage can reasonably be repaired or whether the extent and condition of the affected materials make a larger restoration appropriate. If an insurance claim is involved, we'll help you understand the construction-related information and documentation that may be needed as the process moves forward." }, { title: "Plan the Restoration", text: "Once the scope of work is established, we'll help you select the appropriate materials and build a clear plan for restoring your home." }, { title: "Restore", text: "We'll manage the project, communicate with you throughout the work, and make sure the restoration is completed to the standards we expect for every Centerline project." }, { title: "Inspect & Walk Through", text: "After the work is complete, we'll inspect the finished project, make sure the jobsite is thoroughly cleaned, and walk the completed work with you so you understand what was done and can ask any remaining questions." },
      ] },
      { type: "faq", heading: "Storm Damage FAQs", faqs: [
        { question: "Should I have my roof inspected after a hail or windstorm?", answer: "If your property experienced significant hail, high winds, falling debris, or other severe weather, an inspection can help determine whether the roof or exterior sustained damage that isn't readily visible from the ground." }, { question: "Does storm damage always mean I need a new roof?", answer: "No. Some storm damage is localized and may be repairable. Other storms can cause widespread damage that makes replacement more appropriate. We'll evaluate the extent of the damage and the overall condition of the roofing system before recommending a solution." }, { question: "Should I call Centerline or my insurance company first?", answer: "If your home has obvious or significant damage, active water intrusion, or an immediate safety concern, take the necessary steps to protect your home and contact your insurance company as appropriate. If you're simply unsure whether a storm damaged your home, starting with an inspection can help. We'll evaluate the property, document what we find, and give you a clearer understanding of whether there's damage that may warrant involving your insurance company. If you've already started a claim, that's okay too. We can inspect the property and help you through the restoration process from there." }, { question: "Can Centerline meet with my insurance adjuster?", answer: "Yes. When appropriate, we can meet with your adjuster at the property, review the areas where we've documented damage, and provide information about the work needed to properly restore your home." }, { question: "Will insurance pay for my roof replacement?", answer: "That depends on the cause and extent of the damage and the coverage provided by your policy. Our job is to thoroughly inspect and document the damage, help you understand what your home needs, and provide the construction information needed to support a proper restoration. If a claim is involved, we'll help you through that process and work with your adjuster when appropriate." }, { question: "What if I don't see any damage after the storm?", answer: "Storm damage isn't always obvious from the ground. If your home experienced significant hail or wind and you're concerned about the roof or exterior, an inspection can help determine whether anything needs attention." },
      ] },
    ], serviceAreaHeading: "Storm Damage Restoration in Zionsville & Central Indiana", serviceAreaText: "Centerline Roofing & Exteriors provides storm damage inspections and restoration services throughout Zionsville, Carmel, Westfield, Whitestown, Brownsburg, Lebanon, and surrounding Central Indiana communities.", finalTitle: "Think Your Home May Have Storm Damage?", finalText: "Start with an inspection. We'll evaluate your roof and exterior, document what we find, answer your questions, and help you understand the right next step for your home.", finalButton: "Request a Free Storm Damage Inspection",
  },
  {
    slug: "gutters", navTitle: "Gutters", title: "Gutter Installation in Zionsville & Central Indiana | Centerline",
    description: "Centerline installs residential gutter systems designed for effective drainage, lasting performance and the needs of your Central Indiana home.", h1: "A Better Gutter System Starts With Managing Water the Right Way",
    intro: ["A well-designed gutter system does more than keep rainwater from pouring off your roof. It collects water from your roof and directs it away from your home, helping protect your roofline, siding, landscaping, and foundation.", "We'll evaluate your home and help you choose a gutter system designed for effective drainage and lasting performance. We'll also consider how the system fits your home's exterior, with options in materials, profiles, colors, and finishes that can complement—and when desired, enhance—the appearance of your home."], heroButton: "Request a Free Estimate",
    sections: [
      { type: "cards", heading: "Your Gutters Are Part of Your Home's Water-Management System", intro: ["During a heavy rain, a large amount of water can move across your roof in a short period of time. Your gutter system has an important job: collect that water, move it efficiently through the system, and discharge it where it can drain safely away from the home.", "When gutters aren't working properly, water can overflow, collect around the home, repeatedly run across exterior surfaces, or contribute to moisture problems along the roof edge and fascia."], cards: [
        { title: "Protect the Foundation", text: "Properly directed downspouts help move roof runoff away from the home instead of allowing water to collect near the foundation." }, { title: "Protect Siding & Exterior Surfaces", text: "Managing roof runoff helps reduce repeated water exposure, staining, and water splashing against siding and other exterior surfaces." }, { title: "Protect Landscaping", text: "Controlling where roof water is discharged can help reduce erosion, washout, and damage around landscaping and planting beds." }, { title: "Protect the Roofline", text: "A properly functioning gutter system helps move water away from the roof edge, fascia, and other vulnerable areas of the home's exterior." },
      ] },
      { type: "checklist", heading: "When Is It Time to Repair or Replace Your Gutters?", body: ["A gutter system doesn't have to be falling off the house to have a problem. Leaks, poor drainage, improper pitch, damaged sections, or gutters that can't effectively manage the water coming off the roof can all affect how the system performs.", "We'll evaluate the condition of the existing system and help determine whether a repair makes sense or whether replacement would provide a better long-term solution."], checklistHeading: "Signs Your Gutters May Need Attention", items: ["Gutters overflowing during rain", "Sagging or pulling away from the home", "Leaking seams or joints", "Cracked, bent, or damaged sections", "Water collecting near the foundation", "Erosion or washout beneath downspouts", "Water staining or repeated moisture on siding or fascia", "Gutters that don't appear to drain properly"] },
      { type: "feature", heading: "A Gutter System Should Be Designed Around Your Home", body: ["Not every home handles water the same way. Roof size and design, rooflines, valleys, drainage areas, downspout locations, surrounding landscaping, and where water can safely discharge all affect how a gutter system should be planned.", "We'll look at the home as a whole and help determine the right gutter and downspout configuration for effective water management without overlooking how the finished system will look on your home.", "The goal isn't simply to install gutters. It's to create a system that moves water where it needs to go and looks like it belongs on your home."] },
      { type: "cards", heading: "The Details Determine How Well the System Works", cards: [
        { title: "Proper Water Flow", text: "Gutters need to be positioned and pitched so water moves efficiently toward the downspouts without unnecessary standing water or overflow." }, { title: "Downspout Placement & Drainage", text: "Downspouts need to handle the water collected by the gutter system and discharge it in locations that help move water safely away from the home." }, { title: "Secure Installation", text: "The gutter system should be properly supported and securely attached so it can perform through rain, wind, snow, and changing Indiana weather." }, { title: "Clean Finished Appearance", text: "Gutters are highly visible on many homes. We'll consider color, placement, rooflines, and exterior details so the system performs well without looking like an afterthought." },
      ] },
      { type: "cards", heading: "Choosing the Right Gutter System", intro: ["The right gutter system starts with understanding how much water your home needs to manage and where that water needs to go. From there, we'll help you consider the materials, appearance, and maintenance options that make sense for your home."], cards: [
        { title: "The Right Size & Capacity", text: "Your gutter system needs enough capacity to manage the water coming off your roof. We'll consider roof size, pitch, drainage areas, valleys, and other factors to help determine the appropriate gutter size and capacity for your home." }, { title: "Downspouts & Drainage", text: "The gutter is only one part of the system. Downspout size, placement, and where the water ultimately drains all affect how well the system performs. We'll consider the complete path water takes from your roof to the ground." }, { title: "Materials, Appearance & Protection", text: "Once we've determined what your home needs to manage water effectively, we'll help you consider the options that matter to you—from materials, profiles, colors, and finishes to gutter protection. Whether your priority is simply a clean, finished look or something that adds to your home's architecture, we'll help you choose a system that fits your home." },
      ] },
      { type: "process", heading: "What to Expect From Centerline", steps: [
        { title: "Evaluate", text: "We'll look at your existing gutters, roof drainage, downspout locations, and the areas where water is being discharged to understand what your home needs." }, { title: "Recommend", text: "We'll explain what we find and help you choose the appropriate gutter system, configuration, and options for your home." }, { title: "Install", text: "We'll coordinate the project and make sure the gutter system is installed with attention to drainage, secure attachment, function, and appearance." }, { title: "Review", text: "We'll review the completed system, make sure the jobsite is clean, and walk through the finished project with you." },
      ] },
      { type: "faq", heading: "Gutter FAQs", faqs: [
        { question: "How do I know if I need new gutters?", answer: "It depends on the condition and performance of your existing system. Sagging, leaking, overflowing, damaged sections, poor drainage, or water consistently ending up where it shouldn't are all reasons to have the system evaluated. Sometimes a repair may solve the problem; other situations may make replacement the better long-term option." }, { question: "What size gutters does my home need?", answer: "The appropriate size depends on factors such as the roof area, roof design, the amount of water being directed to particular sections, and the downspout configuration. Rather than assuming one size is right for every home, we'll help determine the system that makes sense for yours." }, { question: "Do I need gutter guards?", answer: "Not every home does. Tree coverage, the type and amount of debris around the home, roof design, maintenance preferences, and the gutter system itself can all affect whether gutter protection is worthwhile. Gutter guards can reduce debris and maintenance, but no system should be considered completely maintenance-free." }, { question: "Where should my downspouts drain?", answer: "The goal is to move water away from the home to an appropriate drainage area rather than allowing it to collect near the foundation. The right solution depends on the property, grading, landscaping, and existing drainage. Downspout extensions, underground drainage, and other solutions may be appropriate depending on the home." }, { question: "Can you replace my gutters when you replace my roof?", answer: "Yes. A roof replacement is a good opportunity to evaluate the entire roof edge and drainage system. If your existing gutters are damaged, undersized, nearing the end of their useful life, or simply don't perform or look the way you want, we can determine whether it makes sense to replace them as part of the project. If your existing gutters are in good condition and functioning properly, we'll tell you that too." },
      ] },
    ], serviceAreaHeading: "Gutter Installation in Zionsville & Central Indiana", serviceAreaText: "Centerline Roofing & Exteriors provides gutter installation and replacement throughout Zionsville, Carmel, Westfield, Whitestown, Brownsburg, Lebanon, and surrounding Central Indiana communities.", finalTitle: "Make Sure the Water Coming Off Your Roof Has Somewhere to Go.", finalText: "Whether your existing gutters aren't performing properly or you're looking for a new system to complement your home, we'll evaluate what you need, explain your options, and help you choose the right solution.", finalButton: "Request a Free Estimate",
  },
  {
    slug: "siding", navTitle: "Siding", title: "Siding Installation in Zionsville & Central Indiana | Centerline",
    description: "Centerline helps Central Indiana homeowners select and install siding for lasting performance, protection and a finished look that fits the home.", h1: "Beautiful Siding. Lasting Protection. The Right Fit for Your Home.",
    intro: ["New siding can completely transform the look of your home while providing lasting protection from the elements. We'll help you choose the right combination of material, performance, color, profile, and design to create an exterior that looks exceptional and is built to perform for years to come.", "Whether you're replacing damaged or aging siding or simply ready to update your home's exterior, we'll help you compare the options and choose a solution that fits your home, your goals, and the investment you want to make."], heroButton: "Request a Free Estimate",
    sections: [
      { type: "cards", heading: "Great Siding Should Look Good and Perform Even Better", intro: ["Siding makes up a significant portion of what you see when you look at a home, so choosing the right system can make a dramatic difference in its appearance. But what's behind that finished exterior matters just as much.", "A quality siding system should protect your home from Indiana weather, manage moisture properly, stand up to years of exposure, and maintain the appearance you chose it for in the first place."], cards: [
        { title: "Weather Protection", text: "A properly installed siding system helps protect the home's exterior from rain, wind, moisture, and changing weather conditions." }, { title: "Durability", text: "The right siding should be selected with long-term performance in mind, including how it handles weather exposure, impact, maintenance, and normal aging." }, { title: "Exterior Appearance", text: "Color, profile, texture, trim, and other details can dramatically change the character of your home. We'll help you consider how those choices work together to create the finished look you want." }, { title: "A Complete Exterior System", text: "Siding works together with housewrap or other water-resistive barriers, flashing, trim, windows, doors, and other exterior details to help protect the structure behind it." },
      ] },
      { type: "checklist", heading: "Is It Time to Repair or Replace Your Siding?", body: ["Not every siding problem requires replacing the entire exterior. Localized damage may be repairable, while widespread deterioration, recurring problems, storm damage, or a planned exterior transformation may make replacement the better solution.", "We'll evaluate the condition of your existing siding, identify areas of concern, and help you understand the options for your home."], checklistHeading: "Signs Your Siding May Need Attention", items: ["Cracked, broken, loose, or missing siding", "Warping, buckling, or other visible distortion", "Storm or impact damage", "Rot, deterioration, or moisture-related concerns", "Loose or damaged trim", "Frequent repairs or increasing maintenance needs", "Fading or an exterior appearance you want to update", "Siding approaching the end of its useful life"] },
      { type: "feature", heading: "The Right Choice Is About More Than Color", body: ["Choosing siding involves more than finding a color you like. Different materials and systems can vary significantly in appearance, durability, maintenance, texture, profiles, cost, and long-term performance.", "Your home's design matters too. The siding, trim, roof, gutters, windows, masonry, and other exterior elements should work together to create a finished exterior that feels intentional and cohesive.", "We'll help you understand the differences, determine which ones matter for your home, and choose a siding system that gives you the right combination of appearance, performance, and value."] },
      { type: "cards", heading: "Great Siding Projects Are About the Details", cards: [
        { title: "Proper Installation", text: "Even high-quality siding depends on proper installation. Attachment, spacing, transitions, flashing, clearances, and other details all affect long-term performance." }, { title: "Water Management", text: "Siding isn't intended to be the home's only defense against water. Proper flashing, water-resistive barriers, and detailing around windows, doors, penetrations, and transitions are important parts of the exterior system." }, { title: "Trim & Transitions", text: "Corners, windows, doors, rooflines, soffits, fascia, and transitions between materials all contribute to both the performance and finished appearance of the project." }, { title: "A Cohesive Finished Exterior", text: "We'll consider how siding colors, profiles, trim, roofing, gutters, masonry, and other visible elements work together so the finished project feels cohesive and fits the character of your home." },
      ] },
      { type: "cards", heading: "Choosing a Siding System", intro: ["There isn't one siding product that's right for every home—or every homeowner. We'll help you compare the options based on appearance, performance, durability, maintenance, and investment so you understand what you're getting and can decide where the differences matter to you."], cards: [
        { title: "Performance & Durability", text: "We'll help you understand how different siding options perform, how they're designed to hold up over time, and what those differences mean for your home." }, { title: "Profiles, Colors & Design", text: "Siding can dramatically change the appearance of a home. Different profiles, textures, colors, trim details, and accent materials can preserve its existing character or help create an entirely new look." }, { title: "The Right Investment", text: "Higher-end materials can offer advantages in appearance, durability, maintenance, and long-term performance—but the most expensive option isn't automatically the right one for every project. We'll help you understand what you're gaining at different investment levels and choose the solution that makes sense for your home and priorities." },
      ] },
      { type: "process", heading: "What to Expect From Centerline", steps: [
        { title: "Evaluate", text: "We'll start by understanding your concerns, what you want to accomplish with your home, and the condition of the existing siding and exterior." }, { title: "Explain & Recommend", text: "We'll explain what we find and help you understand whether repair or replacement makes sense and which siding options are appropriate for your home." }, { title: "Select & Plan", text: "We'll help you work through materials, colors, profiles, trim, and other design details, explain the differences between your options, and establish a clear plan for the project." }, { title: "Install", text: "We'll coordinate the project and make sure the siding system is installed with attention to the details that affect performance, durability, and finished appearance." }, { title: "Inspect & Walk Through", text: "Once the project is complete, we'll inspect the finished work, make sure the property is cleaned up, and walk through the project with you." },
      ] },
      { type: "faq", heading: "Siding FAQs", faqs: [
        { question: "How do I know whether my siding needs to be repaired or replaced?", answer: "That depends on the type of siding, age, extent of the damage, condition of the surrounding materials, and whether compatible replacement material is available. We'll evaluate the siding first and recommend a repair when a repair is the practical solution." }, { question: "What type of siding is best for my home?", answer: "There isn't one answer that's right for every home. Appearance, material performance, maintenance, architecture, budget, and your long-term goals all matter. We'll help you understand the differences and choose the option that makes the most sense for your home." }, { question: "What should I do if my siding was damaged by a storm?", answer: "Start by having the damage evaluated. Wind, hail, and flying debris can affect siding differently depending on the material and severity of the storm. We'll inspect the affected areas, document what we find, and help you understand whether the damage can be properly repaired or whether a larger restoration is appropriate. If insurance is involved, we'll also help you understand what to expect from that process.", link: { label: "Learn About Storm Damage Restoration", href: "/storm-damage-restoration" } }, { question: "Can you coordinate siding with a new roof and gutters?", answer: "Yes. When you're completing multiple exterior improvements, planning them together gives us an opportunity to consider how the roofing, siding, gutters, trim, colors, and other details work together both functionally and visually." },
      ] },
    ], serviceAreaHeading: "Siding Installation in Zionsville & Central Indiana", serviceAreaText: "Centerline Roofing & Exteriors provides siding installation, replacement, and repair throughout Zionsville, Carmel, Westfield, Whitestown, Brownsburg, Lebanon, and surrounding Central Indiana communities.", finalTitle: "Protect Your Home. Make It Look Like Yours.", finalText: "Whether your siding is damaged, showing its age, or you're ready to transform the look of your home's exterior, we'll help you understand your options and choose the right solution for your home.", finalButton: "Request a Free Estimate",
  },
];
